before_install:
  - yes | sudo add-apt-repository ppa:hansjorg/rust
  - sudo apt-get update
install:
  - sudo apt-get install rust-nightly
  - sudo apt-get install libXxf86vm-dev
script:
  - git clone https://github.com/glfw/glfw.git
  - cd glfw
  - git checkout 3.0.3
  - cmake -DBUILD_SHARED_LIBS=ON
  - make
  - sudo make install
  - cd ..
  - git submodule init
  - git submodule update
  - make deps
  - make
  - make test
